[workspace]
resolver = "3"
members = ["libwild-proxy", "wild-proxy"]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
license = "MIT OR Apache-2.0"

# Uncomment this to use Wild from the local repository
#[patch.crates-io]
#libwild = { path = "../wild/libwild" }
